name: pipeline

on:
  push:
    branches: [main]

jobs:
  release:
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yml@main
    secrets: inherit

  build:
    needs: [release]
    if: needs.release.outputs.version != ''
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-build.yml@main

  push:
    needs: [build]
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-push.yml@main
    secrets: inherit
    with:
      version: ${{ needs.release.outputs.version }}
