name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-build.yml@main
    with:
      solution: app/*.slnx

  push:
    needs: [build]
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-push.yml@main
    secrets: inherit
    with:
      solution: app/*.slnx
      version: ${{ needs.build.outputs.version }}
